### PR TITLE
Add missing dependencies, update for wdio@6 support

### PR DESCRIPTION
**Pull request by webOS101**
This adds missing dependencies and allows this to work with wdio@6.

### CODE REVIEW

**Comment by webOS101** [comment]
Optionally, you could bump the major version number and migrate all the to v6.  You could also merge this change without the '|| ^6.0.0' for logger and _then_ make a v6 version.

**Comment by Jnegrier** [comment]
Hi @webOS101 thanks for your PR, I'll take a look later today 👍

**Comment by webOS101** [comment]
Thanks! Let me know if there's anything I can do to help.

**Comment by webOS101** [comment]
I was just thinking that maybe the logger should be in `peerDependencies` (and `devDependencies`) so that it can use the one from the wdio install.  I didn't test that, though.

**Comment by Jnegrier** [comment]
I will publish a new version with these changes, will have to take a look at the other dependencies and fix those checks in Travis, Thanks @webOS101 !

**Pull request merged**
